feat: processorの分割
jaoafa/VCSpeaker.kt pull request #156
Opened 2024-06-16 16:15 UTC by book000

2024-06-17 23:13 UTC, book000 commented
https://kotest.io/docs/framework/integrations/mocking.html

2024-06-18 14:10 UTC, book000 commented
HttpClient.getをmockすればいいのか？

![image](https://github.com/jaoafa/VCSpeaker.kt/assets/8929706/e2a29107-7f1e-416f-ae64-8d60d622f94e)

2024-06-23 09:56 UTC, book000 commented
画像ファイルの文字起こし処理テストに断念。とりあえずメモ

```kotlin

    test("download") {
        // 画像ファイル image.png
        mockkStatic("com.kotlindiscord.kord.extensions.utils._AttachmentsKt")
        val attachment = mockk<Attachment>()
        every { attachment.isImage } returns true
        every { attachment.isSpoiler } returns false
        every { attachment.filename } returns "image.png"
        coEvery { attachment.download() } returns byteArrayOf(0x00)

        // VisionApi
        mockkObject(VisionApi)
        every { VisionApi.isGoogleAppCredentialsExist() } returns true
        every { VisionApi.getTextAnnotations(any()) } returns listOf(
            VisionTextAnnotation(
                "test",
                "ja",
                1.0f,
                listOf(VisionVertex(0, 0), VisionVertex(0, 0), VisionVertex(0, 0), VisionVertex(0, 0))
            )
        )
        every { VisionApi.drawTextAnnotations(any()) } returns mockk<ImmutableImage> {
            every { output(any<PngWriter>(), any<File>()) } returns mockk()
        }

        mockkObject(VCSpeaker)
        every { VCSpeaker.storeFolder } returns File("./store-test")

        mockkObject(VisionApiCounterStore)
        every { VisionApiCounterStore.get() } returns mockk {
            every { count } returns 0
        }
        every { VisionApiCounterStore.increment() } just Runs

        mockkStatic("dev.kord.core.behavior.MessageBehaviorKt")
        val message = mockk<Message>()
        coEvery { message.reply(any()) } returns mockk<Message>()
        every { message.attachments } returns setOf(attachment)

        val voice = Voice(speaker = Speaker.Hikari)

        val (processedText, processedVoice) = AttachmentProcessor().process(message, "test", voice)

        processedText shouldBe "test 画像ファイル image.png "
        processedVoice shouldBe voice
    }
```

2024-06-23 10:49 UTC, book000 commented
@yuuahp 
レビューをお願いします。基本的にはテストの追加ばっかりですが、PRあたりの変更がかなり大きくなってしまいごめんなさい

それはそれとして、assign reviewは相変わらずエラーです
https://github.com/jaoafa/VCSpeaker.kt/actions/runs/9632849766/job/26566534103

2024-06-25 01:15 UTC, yuuahp commented
もしかしてコミットされるとその部分のレビューのドラフト消える？

2024-06-25 09:29 UTC, book000 commented
うそお！？

2024-06-30 11:49 UTC, yuuahp requested changes
テストケース名のレビューは途中なので無視してください

2024-06-30 12:15 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
> +        val (processText, processVoice) = process(message, text, voice)
ここで出力されるvoiceは、inlineVoice以外の理由で変わっているケース（Markdownとか）も今後あるので、inlineVoiceという変数命名は避けたいです。
process**ed**Text, process**ed**Voice でどうでしょう？

2024-06-30 12:51 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
> +        }
fold文を使うように直しました。

2024-06-30 12:52 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/BaseProcessor.kt
> +    private var isImmediately: Boolean = false
修正しました。

2024-06-30 12:53 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/BaseProcessor.kt
> +    fun isImmediately() = isImmediately
修正しました。

2024-06-30 12:56 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/IgnoreAfterReplaceProcessor.kt
features/Ignore.kt を作り、shouldIgnoreOnをまとめました。

2024-06-30 13:09 UTC, book000 commented on src/test/kotlin/processors/AttachmentProcessorTest.kt
attachmentに寄せました

2024-06-30 13:24 UTC, book000 commented on src/test/kotlin/processors/InlineVoiceProcessorTest.kt
> +    test("If an invalid emotion level is specified, the value is ignored without throwing an exception.") {
例外が出ないことを検証するテストになるので、上側でよさそうです。

2024-06-30 13:35 UTC, book000 commented on src/test/kotlin/processors/ReplacerProcessorTest.kt
> +        test("For unknown role mentions, replace with an unknown role.") {
```suggestion
        test("If unknown roles are mentioned, they should be replaced as unknown roles.") {
```

2024-06-30 13:35 UTC, book000 commented on src/test/kotlin/processors/ReplacerProcessorTest.kt
> +        test("For unknown user mentions, replace with an unknown user.") {
```suggestion
        test("If unknown users are mentioned, they should be replaced as unknown users.") {
```

2024-07-01 01:39 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
> +        val (processText, processVoice) = process(message, text, voice)
それはそうかも
でも processedVoice だと voice が処理されたみたいになりませんか？
effectiveVoice とかはだめですか？

2024-07-01 02:38 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
> +        val (processText, processVoice) = process(message, text, voice)
処理された結果としての "Text"、"Voice" のイメージでいます

effectiveVoiceって、効果的なvoice？有効なvoice？的な意味合いですかね？
なんか諸々の処理を行った結果としてのvoice、という意味合いかなと思ってたんですが…うーん。

2024-07-07 02:27 UTC, yuuahp approved these changes

2024-07-07 02:53 UTC, merged