feat: URLに関する置換処理を作成
jaoafa/VCSpeaker.kt pull request #31
Opened 2023-10-09 14:38 UTC by book000

*description writing*

2023-10-09 15:24 UTC, book000 commented
CIが落ちていますが、これは #32 によるものです。

2023-10-10 12:34 UTC, yuuahp requested changes
コード以外
- models/response 以下は discord/ twitter/ などのパッケージに分かれているのに、models/original でなっていないのはなぜですか？
- TwitterOembed じゃなくて TwitterOEmbed ではないでしょうか
-

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +        return null
```suggestion
        return if (isThread)
            channel.asChannelOf<ThreadChannel>()
        else null
```
と書けます

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +        val url = "https://discord.com/api/invites/${inviteId}"
```suggestion
        val url = "https://discord.com/api/invites/$inviteId"
```
`.` も ` ` も入らない変数と式は `{}` を省略できます

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            }
```suggestion
            if (eventId != null)
                parameter("guild_scheduled_event_id", eventId.value)
```
一行 if は見やすさにもよりますが `{}` 省略しちゃっていいと思います

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                    event.let { it?.name },
```suggestion
                    event?.id?.let { Snowflake(it) },
                    event?.name
```
謎の let な気がします

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +    }
```suggestion
    private fun getExtension(url: String) = try {
        val urlObj = URL(url)
        val path = urlObj.path
        val lastDot = path.lastIndexOf('.')
        if (lastDot == -1) null else path.substring(lastDot + 1)
    } catch (e: MalformedURLException) {
        null
    }
```
即 return は省略できます

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                "${channelType}「${thread.name}」のスレッド「${thread.parent.asChannel().name}」で送信したメッセージのリンク"
```suggestion
                "$channelType「${thread.name}」のスレッド「${thread.parent.asChannel().name}」で送信したメッセージのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                "${channelType}「${channel.name}」で送信したメッセージのリンク"
```suggestion
                "$channelType「${channel.name}」で送信したメッセージのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                "${channelType}「${thread.parent.asChannel().name}」のスレッド「${thread.name}」へのリンク"
```suggestion
                "$channelType「${thread.parent.asChannel().name}」のスレッド「${thread.name}」へのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                "${channelType}「${channel.name}」へのリンク"
```suggestion
                "$channelType「${channel.name}」へのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +                "ユーザー「${userName}」のツイートへのリンク"
```suggestion
                "ユーザー「$userName」のツイートへのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            val replaceTo = "${tweet.authorName.removeEmojis()}のツイート「${tweetContent}」へのリンク"
```suggestion
            val replaceTo = "${tweet.authorName.removeEmojis()}のツイート「$tweetContent」へのリンク"
```

2023-10-10 12:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            val replaceTo = "Webページ「${shortTitle}」へのリンク"
```suggestion
            val replaceTo = "Webページ「$shortTitle」へのリンク"
```

2023-10-10 12:42 UTC, yuuahp requested changes
追加

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UserMentionReplacer.kt
> +    override suspend fun replace(text: String, guildId: Snowflake): String =
```suggestion
    override suspend fun replace(text: String, guildId: Snowflake) =
```
型は推測してくれます

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/RoleMentionReplacer.kt
> +    override suspend fun replace(text: String, guildId: Snowflake): String =
```suggestion
    override suspend fun replace(text: String, guildId: Snowflake) =
```
型は推測してくれます

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/RegexReplacer.kt
> +    override suspend fun replace(text: String, guildId: Snowflake): String =
```suggestion
    override suspend fun replace(text: String, guildId: Snowflake) =
```
型は推測してくれます

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/ChannelMentionReplacer.kt
> +    override suspend fun replace(text: String, guildId: Snowflake): String =
```suggestion
    override suspend fun replace(text: String, guildId: Snowflake) =
```
型は推測してくれます

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/AliasReplacer.kt
> +    override suspend fun replace(text: String, guildId: Snowflake): String =
```suggestion
    override suspend fun replace(text: String, guildId: Snowflake) =
```
型は推測してくれます

2023-10-10 12:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/Emoji.kt
> +
```suggestion
    fun String.removeEmojis() = emojis.fold(this) { replaced, emoji ->
        replaced.replace(emoji.unicode, "")
    }

```
さっきのと同じですが、私もやってたので後で直しておきます

2023-10-10 13:15 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            channel.type == ChannelType.PrivateThread || channel.type == ChannelType.PublicGuildThread || channel.type == ChannelType.PublicNewsThread
fixed

2023-10-10 13:15 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            channel.type == ChannelType.PrivateThread || channel.type == ChannelType.PublicGuildThread || channel.type == ChannelType.PublicNewsThread
fixed

2023-10-10 13:16 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +        return null
fixed

2023-10-10 13:17 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> +            }
これは好み分かれそうですがはい

2023-10-10 13:25 UTC, book000 commented
クソ大量にcommitしてしまったのでマージするときはsquashでお願いします（デフォルトでsquashでもいいと思うけど）

2023-10-10 13:34 UTC, book000 commented
できれば、なにかしらフォーマッタできる設定が入ると嬉しいわね…。IDEAのフォーマット設定とか

2023-10-11 13:33 UTC, yuuahp commented
> できれば、なにかしらフォーマッタできる設定が入ると嬉しいわね…。IDEAのフォーマット設定とか

どういう？
EditorConfigみたいな？

2023-10-11 13:39 UTC, yuuahp commented
> > models/response 以下は discord/ twitter/ などのパッケージに分かれているのに、models/original でなっていないのはなぜですか？
> 
> たしかに...。models/responses/*.kt とするか、discord/ twitter/ でパッケージを分けるか、どちらがお好みですか？

パッケージ名の方が密度低いと思うので分けたいです

2023-10-11 13:42 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/Discord.kt
> +        ).contains(channel.type)
```suggestion

    fun Channel.isThread() =
        listOf(
            ChannelType.PrivateThread,
            ChannelType.PublicGuildThread,
            ChannelType.PublicNewsThread
        ).contains(type)
```
拡張関数とかいかがでしょう

2023-10-11 13:53 UTC, book000 commented
フォーマット設定はこの辺を想像しています
ja: https://pleiades.io/help/idea/configuring-code-style.html
en(official): https://www.jetbrains.com/help/idea/configuring-code-style.html

2023-10-11 14:01 UTC, book000 commented
気になってるところとして、この辺がunused argumentになるのが気になるんですよねえ。いつもコミット時に怒られる
![image](https://github.com/jaoafa/VCSpeaker.kt/assets/8929706/5bc4bb2d-522e-4a69-abdf-e43e13c58d09)

2023-10-11 22:57 UTC, yuuahp commented
> フォーマット設定はこの辺を想像しています ja: https://pleiades.io/help/idea/configuring-code-style.html en(official): https://www.jetbrains.com/help/idea/configuring-code-style.html

デフォルトじゃ足りないところがある感じですか？

2023-10-11 23:02 UTC, book000 commented
たとえぱ、指摘いただいたRegexの改行とかってIDEAの自動フォーマットをかけた上でアレなんですよね（デフォルトは一定文字数を漏れた行だけが改行される仕様だったはず）
なのでお好みな形に設定してもらえればレビュー負荷下がるかなあと

2023-10-11 23:02 UTC, yuuahp commented
> 気になってるところとして、この辺がunused argumentになるのが気になるんですよねえ。いつもコミット時に怒られる ![image](https://user-images.githubusercontent.com/8929706/274299493-5bc4bb2d-522e-4a69-abdf-e43e13c58d09.png)

諦めて処理を2種類に分けるか、アノテーションで無視するかだと思います

2023-10-11 23:03 UTC, yuuahp commented
> たとえぱ、指摘いただいたRegexの改行とかってIDEAの自動フォーマットをかけた上でアレなんですよね（デフォルトは一定文字数を漏れた行だけが改行される仕様だったはず） なのでお好みな形に設定してもらえればレビュー負荷下がるかなあと

やってみます

2023-10-11 23:06 UTC, book000 commented
unused argumentのところ、引数1つと2つ両方受け付けますよみたいな書き方ないですかね？

2023-10-11 23:08 UTC, book000 commented
アノテーションかけるとそのメソッド全体でかかる気がしててなんかちょっとですよねえ

2023-10-11 23:50 UTC, yuuahp commented
この前 reflect で無理やり入れられないかと思って試してみましたが無理でした

2023-10-12 13:57 UTC, book000 commented
一応、guildIdのunused対応はこのPRの対象外とさせてください。

2023-10-12 23:01 UTC, yuuahp approved these changes
じゃあマージします

2023-10-12 23:23 UTC, merged