fix: title not reset on afk
jaoafa/VCSpeaker.kt pull request #53
Opened 2023-11-08 14:22 UTC by yuuahp

VC に参加している最後の一人が AFK となった場合にタイトルがリセットされない問題を解決しました。

2023-11-08 23:14 UTC, book000 requested changes

2023-11-08 23:14 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/events/TitleResetEvent.kt
> +                failIf(event.old?.getChannelOrNull() == null || (currentChannel != null && !currentChannel.isAfk()))
この条件式だと、「残り1人のvcからafkに移動した場合」はリセットされますが、「残り1人のvcから他のafkではないvcに移動した場合」にリセットされないように見られます
（チェックアウトして試しましたが、リセットされませんでした…）

タイトルがリセットされる条件は「vcの退出、または移動によってvc人数がbotを含まずに0人になる場合」なので、そもそも以下で良いのではないでしょうか？

```suggestion
                failIf(event.old?.getChannelOrNull() == null)
```

※適当なこと言ってたらごめんなさい

2023-11-09 00:40 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/events/TitleResetEvent.kt
> +                failIf(event.old?.getChannelOrNull() == null || (currentChannel != null && !currentChannel.isAfk()))
そうかもしれない…
AFK のことしか意識してなかったわ

2023-11-09 05:54 UTC, book000 commented
後ほど、動作確認して問題なさそうならapprove+mergeします。

2023-11-09 13:39 UTC, book000 requested changes

2023-11-09 13:39 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/events/TitleResetEvent.kt
> +                val currentChannel = event.state.getChannelOrNull()
これ、unusedじゃない？（今朝のサジェストにいれてなくてごめんだけど）

2023-11-09 14:34 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/events/TitleResetEvent.kt
> +                val currentChannel = event.state.getChannelOrNull()
unused でした

2023-11-09 14:34 UTC, yuuahp commented
✅

2023-11-09 21:35 UTC, book000 approved these changes

2023-11-09 21:35 UTC, merged