feat: vcテキストチャンネルに画像が投稿された場合に、文字起こしする
jaoafa/VCSpeaker.kt pull request #70
Opened 2024-03-05 16:09 UTC by book000

*Pending*

2024-03-05 16:25 UTC, book000 commented
ローカルだとビルドできるので、なんで…？です

2024-03-05 16:29 UTC, book000 commented
gitignoreにスラッシュがなかったせいでコミットされてなかった…

2024-03-06 01:57 UTC, yuuahp requested changes

2024-03-06 01:57 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
https://github.com/JourneyHQ/DynmapProcessor/blob/6e532d316a759975fd12fde8550e743ac5c41a86/src/main/kotlin/MapImage.kt#L324
FilledRect で描けます
あと、`draw(FilledRect{}, Text{})` みたいにできます

2024-03-06 03:40 UTC, book000 commented
一点、知見あれば教えてください

- 文字の縁取りをするにはどうしたら良い？白文字黒縁取りにしようとしたんだけど、うまくいってない気がする

2024-03-06 03:41 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
FilledRectってfillだから塗り潰されないですかね？

2024-03-06 03:46 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
FilledじゃないRectがあったりするかしら？

2024-03-06 03:51 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
あ普通の Rect もある
DynmapProcessor で半透明塗りつぶししてたので

2024-03-06 03:59 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
ならほど。maxとminとってRectするようにします

2024-03-06 04:01 UTC, yuuahp commented
使ったことない...
細すぎて見えなくなってるとか？コード見た感じ間違ってなさそうだけど

2024-03-06 06:49 UTC, book000 commented
うーん…退勤したら色々試してみるか…

2024-03-06 09:49 UTC, book000 commented
えぐいコード書かせようとしてくる

https://chat.openai.com/share/be37cf76-8d76-4db7-a056-129e216f0fad

```kotlin
    // 文字列に縁取りを追加
    val outlinedImage = image.awt().graphics.apply {
        color = outlineColor.toAWTColor()
        font = font.deriveFont(fontSize)
        drawString(text, x - 1, y - 1)
        drawString(text, x + 1, y - 1)
        drawString(text, x - 1, y + 1)
        drawString(text, x + 1, y + 1)
    }
```

2024-03-06 10:12 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
> +            })
なおしました

2024-03-06 10:12 UTC, yuuahp commented
> えぐいコード書かせようとしてくる
> 
> https://chat.openai.com/share/be37cf76-8d76-4db7-a056-129e216f0fad
> 
> ```kotlin
>     // 文字列に縁取りを追加
>     val outlinedImage = image.awt().graphics.apply {
>         color = outlineColor.toAWTColor()
>         font = font.deriveFont(fontSize)
>         drawString(text, x - 1, y - 1)
>         drawString(text, x + 1, y - 1)
>         drawString(text, x - 1, y + 1)
>         drawString(text, x + 1, y + 1)
>     }
> ```

草

2024-03-06 10:13 UTC, yuuahp approved these changes

2024-03-06 10:29 UTC, merged