chore: fix timezone & make gradle deps cached
jaoafa/VCSpeaker.kt pull request #81
Opened 2024-03-26 14:30 UTC by yuuahp

- タイムゾーンを Asia/Tokyo に設定しました。
  (ファイルに書き込む方法はなぜか効かなかったので、ENV に設定するようにしました)
- Gradle が依存ライブラリをダウンロードするところまでを、Docker がキャッシュできるようにしました。

2024-03-26 22:42 UTC, book000 requested changes

2024-03-26 22:42 UTC, book000 commented on Dockerfile
> +ENV TZ=Asia/Tokyo
ENVは32行目あたりにまとめて記述してるので、そこに寄せた方がいいかと？

2024-03-26 22:42 UTC, book000 commented on Dockerfile
> +RUN ./gradlew build || return 0
DockerfileはRUNやCOPYごとにレイヤーが作られるので、RUNを連続で書く場合は&&でまとめてください
https://docs.docker.jp/develop/develop-images/dockerfile_best-practices.html#id12

hadolintを入れるとこの辺を警告してくれます

2024-03-26 23:23 UTC, book000 commented on Dockerfile
> +RUN ./gradlew build || return 0
マルチステージングのランナーじゃないから良いのか…なんでもない！

2024-03-27 01:01 UTC, yuuahp commented on Dockerfile
> +ENV TZ=Asia/Tokyo
```
RUN apk add --no-cache libstdc++...
    apk add --update --no-cache tzdata

COPY ...
ENV ...
ENV ...
ENV ...
ENV ...
ENV TZ=Asia/Tokyo

RUN apk del tzdata
```
ということ？

2024-03-28 01:05 UTC, book000 commented on Dockerfile
> +ENV TZ=Asia/Tokyo
ENVについてははい。

apkコマンドについては、libstdc++などにupdateオプションつけない理由はないので、一緒でも良いかもです。

```dockerfile
RUN apk add --update --no-cache libstdc++ ... tzdata
```

2024-03-29 13:05 UTC, book000 commented on Dockerfile
> +ENV TZ=Asia/Tokyo
あーーー。ごめんなさい。うまく伝わってない気がする。Discord#developmentに一連書きました

2024-03-29 14:42 UTC, book000 approved these changes

2024-03-29 15:00 UTC, merged