feat: tests
jaoafa/VCSpeaker.kt pull request #97
Opened 2024-05-19 12:52 UTC by yuuahp

Kotest と MockK によるテストを実装しました。
現在実装されているのは、

- SteamTest
- YouTubeTest
- TextProcessorTest (Ignore, Alias, URL)

です。

あと Actions にテストワークフローを追加しました。
また、Mock しやすいように Config 周りを少し整理しました。

close #94

2024-05-19 13:24 UTC, book000 requested changes

2024-05-19 13:24 UTC, book000 commented on .github/workflows/test.yml
> +name: ✅ Test
好みですけど…、🧪の方がテストっぽくありません？

2024-05-19 13:24 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/api/VoiceTextAPI.kt
> +class VoiceTextAPI(private val token: String) {
ここ、apiKeyからtokenに変更した理由はありますか？
公式のマニュアル https://cloud.voicetext.jp/webapi/docs/api でもトークンではなくAPIキーという扱いですが…。

2024-05-19 13:24 UTC, book000 commented on src/test/kotlin/TextProcessorTest.kt
> +    beforeTest {
この各種ストアのモックって実データいじっちゃう感じですか？
もしいじるならテンポラリパスか何かにしたいなあ…って感じです

2024-05-19 13:24 UTC, book000 commented on src/test/kotlin/TextProcessorTest.kt
> +    context("alias") {
次のテストパターンが欲しいです:

- 置き換え対象文字列が、複数含まれる場合（すべてが置き換えられること）
- エイリアスが複数あり、連鎖的に置き換えられる場合
  - 例えば、"あいうえお" → "かきくけこ“・"かきくけこ" → "さしすせそ" という二つのエイリアスがある時、入力「あいうえお」は「さしすせそ」となるかどうか（あるべき姿がどっちであるべきかという話も必要かもしれません）
- エイリアスによって置き換えられたことにより、除外パターンに該当する場合に読み上げられないこと
  - 例えば、エイリアスでは "お前" → "オレ“ というエイリアスがあり、除外（ignore）には "オレ" があるとき、入力「お前」では読み上げられないこと
  - 逆のパターンとして、エイリアスで "あなた" → "わたし" というエイリアスがあり、除外として "あなた" があるとき、入力「あなた」は読み上げられること
- その他、URL置換などでエイリアス、または除外パターンに合致した時、どういう挙動になるか

2024-05-19 13:26 UTC, yuuahp commented on src/test/kotlin/TextProcessorTest.kt
> +    beforeTest {
実データはいじってません
ファイルには書き込まれないようになってます

2024-05-19 13:27 UTC, book000 commented on src/test/kotlin/TextProcessorTest.kt
> +    beforeTest {
オッケーです。じゃあ問題ないですね

2024-05-19 13:29 UTC, yuuahp commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/api/VoiceTextAPI.kt
> +class VoiceTextAPI(private val token: String) {
TokenSpec のように他の場所で Token に統一してたので合わせようかなと
別に動作にかかわる様な変更じゃないので、あれだったら戻します

2024-05-19 13:29 UTC, yuuahp commented on .github/workflows/test.yml
> +name: ✅ Test
言われてみれば

2024-05-19 13:30 UTC, book000 commented on src/main/kotlin/com/jaoafa/vcspeaker/tts/api/VoiceTextAPI.kt
> +class VoiceTextAPI(private val token: String) {
VoiceTextではAPIKeyとは異なるものとしてトークンが必要になるのかと誤認することになるので、よくないかなとは思います

2024-05-19 13:31 UTC, book000 commented on .github/workflows/test.yml
> +name: ✅ Test
あわせて、stepの方のnameも更新した方が良いかもです

2024-05-19 13:40 UTC, book000 commented
あと、Conventional Commitsに即するならprefixは `test` なんですかね…？
`test: テストケースの追加` とか？

2024-05-19 13:41 UTC, yuuahp commented
存在を忘れてました

2024-05-19 13:46 UTC, book000 commented
ふと思ったんですか、src/test/kotlinの下ってsrc/main/kotlinとパッケージ合わせなくて良いんですか？

2024-05-19 13:46 UTC, yuuahp commented
合わせるほど作ってないよな～とおもって合わせませんでした

2024-05-19 13:48 UTC, book000 commented
まあなんか諸々のルールとかあるべき姿として良いなら良いのですが…、よくわからんです

2024-05-19 13:50 UTC, yuuahp commented
パッケージ以下ほとんどテスト作ってるみたいな状況になってきたら test でもパッケージ合わせようかなと思ってます

2024-05-19 13:51 UTC, book000 commented
なるほど、りょーかいです

2024-05-25 09:26 UTC, yuuahp commented on src/test/kotlin/TextProcessorTest.kt
> +    context("alias") {
> エイリアスが複数あり、連鎖的に置き換えられる場合

これ、私は起こらない方がいいと思うんですけどどうでしょう？
扱いも複雑になりすぎるし、ユーザーの意図しない動きになる方が多いかなと

2024-05-25 09:30 UTC, book000 commented on src/test/kotlin/TextProcessorTest.kt
> +    context("alias") {
起こらない方がよさそうではありますが、実装上実現可能なのかなあと思ったりはします

2024-05-25 09:33 UTC, yuuahp commented on src/test/kotlin/TextProcessorTest.kt
> +    context("alias") {
すでに replace された部分を除外して置き換えるようにすれば良いんじゃないかな～って考えたりしてます

2024-05-25 09:39 UTC, book000 commented on src/test/kotlin/TextProcessorTest.kt
> +    context("alias") {
除外する、のがなかなか大変そうではあるけど…。
とりあえずその動作をもし追加するにしても、このPRじゃないかなーと思います。とりあえずは現状の動作についてのテストケースを定義して、別のPRで「連続的にエイリアス処理が行われないようにした」処理にアップデートする感じかと。

2024-05-25 10:23 UTC, book000 approved these changes

2024-05-25 10:23 UTC, merged